package com.ishow.ischool.application;

/**
 * Created by abel on 16/8/22.
 */
public class Resource {
    public static final int NO_NEED_CHECK = 10000;

    public static final int ROLE_PERMISSION_CHENDU = 17;//晨读讲师的角色id
    public static final int USER_LISTS = -1;    //推荐人/办理人/用户列表


    public static final int MARKET_PROCESS = -1;

    public static final String RESOURCE_ID = "resource_id";

    public static final int MARKET_HOME_HOME = 1;                                     //市场业务-------------------------
    public static final int MARKET_STUDENT_STATISTICS = 7;                            //    |—学员统计
    public static final int MARKET_STUDENT_EDITMOBILE = 161;                          //        |—编辑手机号
    public static final int MARKET_STUDENT_ADD = 80;                                  //        |—新增学员
    public static final int MARKET_STUDENT_SENDMESSAGE = 81;                          //        |—发送短信
    public static final int MARKET_STUDENT_OPENPERMISSION = 82;                       //        |—开通APP权限
    public static final int MARKET_STUDENT_STUDENTPAYMENT = 92;                       //        |—学员付款
    public static final int SHARE_REFUND_DOREFUNDM = 149;                             //            |—退款
    public static final int MARKET_STUDENT_STUDENTINFO = 93;                          //        |—学员详情
    public static final int MARKET_STUDENT_EDIT = 110;                                //        |—编辑学员
    public static final int MARKET_STUDENT_EXPORT = 111;                              //        |—导出
    public static final int MARKET_STUDENT_COMMUNICATIONLIST = 138;                   //        |—查看沟通记录
    public static final int SHARE_COMMUNICATION_LIST_ADDM = 139;                      //        |—添加沟通记录
    public static final int MARKET_INVITATION_INDEX = 121;                            //    |—邀约管理
    public static final int MARKET_INVITATION_LIST = 135;                             //        |—邀约列表
    public static final int MARKET_INVITATION_ADD = 122;                              //        |—新建邀约
    public static final int MARKET_INVITATION_SET = 123;                              //        |—设置邀约
    public static final int MARKET_OPENCLASS_INDEX = 8;                               //    |—公开课管理
    public static final int MARKET_OPENCLASS_LIST = 116;                              //        |—公开课列表
    public static final int MARKET_OPENCLASS_SIGNDETAIL = 117;                        //        |—公开课明细表
    public static final int MARKET_OPENCLASS_DETAIL = 118;                            //        |—每节公开课详情
    public static final int MARKET_OPENCLASS_ADD = 119;                               //        |—添加公开课
    public static final int MARKET_OPENCLASS_CHANGESTUDENT = 120;                     //        |—交换学员
    public static final int MARKET_OPENCLASS_EXPORT = 124;                            //        |—导出
    public static final int MARKET_OPENCLASS_EDIT = 126;                              //        |—修改公开课
    public static final int MARKET_OPENCLASS_DELETE = 127;                            //        |—公开课删除
    public static final int MARKET_OPENCLASS_SIGNDELETE = 128;                        //        |—公开课签到删除
    public static final int MARKET_OPENCLASS_QRCODE = 136;                            //        |—查看二维码
    public static final int SHARE_COMMUNICATION_INDEXM = 9;                           //    |—沟通记录
    public static final int SHARE_COMMUNICATION_ADDM = 62;                            //        |—添加沟通记录
    public static final int SHARE_COMMUNICATION_EDITM = 78;                           //        |—编辑沟通记录
    public static final int SHARE_COMMUNICATION_EXPORTM = 98;                         //        |—导出沟通记录
    public static final int SHARE_COMMUNICATION_VIEWM = 100;                          //        |—查看沟通记录
    public static final int SHARE_COMMUNICATION_DELETEM = 112;                        //        |—删除沟通记录
    public static final int SHARE_CLASSCOUNT_INDEXM = 10;                             //    |—课程统计
    public static final int SHARE_CLASSCOUNT_EXPORTM = 140;                           //        |—课程统计导出

    public static final int EDUCATION_HOME_HOME = 2;                                  //教务教学---------------------------
    public static final int EDUCATION_CLASSMANAGEMENT_INDEX = 11;                     //    |—班级管理
    public static final int EDUCATION_CLASSMANAGEMENT_ADD = 88;                       //        |—创建班级
    public static final int SHARE_CHANGECLASS_CHECKCLASSPEOPLENUM = 107;              //            |—检查班级人数
    public static final int EDUCATION_CLASSMANAGEMENT_EDIT = 89;                      //        |—编辑班级
    public static final int EDUCATION_CLASSMANAGEMENT_CLASSRECORD = 90;               //        |—上课记录
    public static final int EDUCATION_CLASSMANAGEMENT_ADDSTUDENT = 91;                //        |—添加学员
    public static final int EDUCATION_CLASSMANAGEMENT_STUDENTDETAIL = 94;             //        |—学员明细
    public static final int EDUCATION_CLASSMANAGEMENT_OPENPERMISSION = 114;           //            |—开通APP权限
    public static final int EDUCATION_CLASSMANAGEMENT_CLASSSIGN = 95;                 //        |—签到
    public static final int EDUCATION_CLASSMANAGEMENT_CLASSSIGNLIST = 96;             //        |—签到表
    public static final int EDUCATION_CLASSMANAGEMENT_EDITSTUDENT = 108;              //        |—编辑学员
    public static final int EDUCATION_CLASSMANAGEMENT_GETCAMPUSRELATE = 134;          //        |—获取校区的相关
    public static final int SHARE_COMMUNICATION_INDEXE = 12;                          //    |—沟通记录
    public static final int SHARE_COMMUNICATION_ADDE = 61;                            //        |—添加沟通记录
    public static final int SHARE_COMMUNICATION_EDITE = 79;                           //        |—编辑沟通记录
    public static final int SHARE_COMMUNICATION_EXPORTE = 99;                         //        |—导出沟通记录
    public static final int SHARE_COMMUNICATION_VIEWE = 101;                          //        |—查看沟通记录
    public static final int SHARE_COMMUNICATION_DELETEE = 113;                        //        |—删除沟通记录
    public static final int SHARE_HOME_HOME = 13;                                     //    |—课程管理
    public static final int SHARE_CLASSCOUNT_INDEXE = 21;                             //        |—课程统计
    public static final int SHARE_CLASSCOUNT_EXPORTE = 141;                           //            |—课程统计导出
    public static final int MARKET_STUDENT_STUDENTINFOE = 142;                        //            |—学生详情
    public static final int EDUCATION_COURSEMANAGEMENT_CHANGE = 22;                   //        |—办理转班/调班
    public static final int SHARE_CHANGECLASS_DOCHANGE = 102;                         //            |—转班/调班
    public static final int EDUCATION_COURSEMANAGEMENT_EXPORTCHANGE = 130;            //            |—导出可转班/调班记录
    public static final int EDUCATION_COURSEMANAGEMENT_SUSPEND = 23;                  //        |—办理停课/复课
    public static final int SHARE_SUSPENDCLASS_DOSUSPEND = 104;                       //            |—操作停课
    public static final int SHARE_SUSPENDCLASS_DORESUME = 105;                        //            |—操作复课
    public static final int EDUCATION_COURSEMANAGEMENT_EXPORTSUSPEND = 131;           //            |—导出可停课/复课记录
    public static final int EDUCATION_COURSEMANAGEMENT_REFUND = 24;                   //        |—办理退费
    public static final int SHARE_REFUND_DOREFUND = 103;                              //            |—操作退费
    public static final int SHARE_REFUND_GETREFUNDACCOUNT = 125;                      //                |—获得退款帐号
    public static final int EDUCATION_COURSEMANAGEMENT_EXPORTREFUND = 132;            //            |—导出可退费名单
    //    public static final int HOME_HOME_HOME = 157;                                     //    |—升学管理
    public static final int EDUCATION_COURSEMANAGEMENT_UPGRADE = 25;                  //        |—办理升学
    public static final int SHARE_UPGRADE_DOUPGRADE = 106;                            //            |—操作升学
    public static final int SHARE_UPGRADE_GETUPGRADECLASS = 115;                      //                |—获得升学的班级列表
    public static final int SHARE_UPGRADE_GETAJAXPRICE = 152;                         //                |—获得升学班级的学费
    public static final int EDUCATION_COURSEMANAGEMENT_EXPORTUPGRADE = 133;           //            |—导出可升学记录
    public static final int SHARE_UPGRADE_DOUPGRADEPAY = 158;                         //            |—升学补款
    public static final int EDUCATION_COURSEMANAGEMENT_UPGRADEREFUND = 159;           //        |—升学退款
    public static final int SHARE_UPGRADE_DOUPGRADEREFUND = 160;                      //            |—升学退款
    public static final int EDUCATION_SUPPLYMANAGEMENT_INDEX = 163;                   //    |—教务教学管理
    public static final int EDUCATION_SUPPLYMANAGEMENT_SIGNUP = 164;                  //        |—补签
    public static final int EDUCATION_SUPPLYMANAGEMENT_MAKEUPLESSON = 165;            //        |—补课

    //    public static final int DATA_HOME_HOME = 3;                               //数据分析----------------------------
//    public static final int DATA_HOME_HOME = 14;                                  //    |—市场业务
    public static final int DATA_DATAANALYZE_BAZAARANALYZE = 26;                      //        |—销售流程分析
    public static final int DATA_DATAANALYZE_BAZAARCONTRAST = 27;                     //        |—各校区业绩对比
    public static final int DATA_DATAANALYZE_BAZAAROTHER = 28;                        //        |—其他类别统计
    public static final int DATA_DATAANALYZE_TEACHINGANALYZE = 15;                    //    |—教务教学
    public static final int DATA_DATAANALYZE_TEACHINGPROCESSANALYSIS = 29;            //        |—教学流程分析
    public static final int DATA_DATAANALYZE_TEACHINGCONTRAST = 30;                   //        |—各校区业绩对比
    public static final int DATA_DATAANALYZE_TEACHINGOTHER = 31;                      //        |—其他类别统计
    public static final int DATA_DATAANALYZE_EDUCATIONALPROCESSANALYSIS = 162;        //        |—教务流程分析
    public static final int HOME_HOME_HOME = 4;                                       //账务统计
    public static final int FINANCE_FINANCE_INDEX = 16;                               //    |—预收退明细表
    public static final int FINANCE_FINANCE_INDEX_PRE = 32;                           //        |—预收款资金
    public static final int FINANCE_FINANCE_MAINLY = 33;                              //        |—主营业务明细
    public static final int FINANCE_FINANCE_REFUND = 34;                              //        |—退款明细
    public static final int HR_HOME_HOME = 5;                                         //人事档案----------------------------
    //    public static final int SYSTEM_HOME_HOME = 6;                             //系统管理----------------------------
    //    public static final int SYSTEM_HOME_HOME = 17;                            //    |—权限管理
    public static final int SYSTEM_ACCOUNTMANAGE_INDEX = 36;                          //        |—员工管理
    public static final int SYSTEM_ACCOUNTMANAGE_ADD = 85;                            //            |—添加员工
    public static final int SYSTEM_ACCOUNTMANAGE_EDIT = 86;                           //            |—修改员工
    public static final int SYSTEM_ACCOUNTMANAGE_DELACT = 87;                         //            |—停用启用员工
    public static final int SYSTEM_ACCOUNTMANAGE_ISHOW = 109;                         //            |—查看员工
    public static final int SYSTEM_POSITION_INDEX = 48;                               //        |—职位管理
    public static final int SYSTEM_POSITION_ADD = 74;                                 //            |—添加职位
    public static final int SYSTEM_POSITION_AUTHORIZE = 75;                           //            |—授权
    public static final int SYSTEM_POSITION_EDIT = 76;                                //            |—修改职位
    public static final int SYSTEM_POSITION_DEL = 77;                                 //            |—删除职位
    public static final int SYSTEM_ROLE_INDEX = 35;                                   //        |—角色管理
    public static final int SYSTEM_ROLE_AUTHORIZE = 63;                               //            |—角色授权
    public static final int SYSTEM_ROLE_EDIT = 64;                                    //            |—修改角色
    public static final int SYSTEM_ROLE_DEL = 65;                                     //            |—删除角色
    public static final int SYSTEM_ROLE_ADD = 66;                                     //            |—添加角色
    public static final int SYSTEM_MENU_INDEX = 47;                                   //        |—菜单管理
    public static final int SYSTEM_MENU_ADD = 67;                                     //            |—添加菜单
    public static final int SYSTEM_MENU_EDIT = 68;                                    //            |—编辑菜单
    public static final int SYSTEM_MENU_DEL = 69;                                     //            |—删除菜单
    public static final int SYSTEM_MENU_TEST = 153;                                   //            |—test
    //    public static final int SYSTEM_HOME_HOME = 18;                            //    |—基本信息管理
    public static final int SYSTEM_SOURCE_INDEX = 37;                                 //        |—来源管理
    public static final int SYSTEM_PAYMETHOD_INDEX = 38;                              //        |—付款方式管理
    public static final int SYSTEM_UNIVERSITY_INDEX = 39;                             //        |—大学管理
    public static final int SYSTEM_UNIVERSITY_ADD = 49;                               //            |—添加大学
    public static final int SYSTEM_UNIVERSITY_EDIT = 50;                              //            |—编辑大学
    public static final int SYSTEM_UNIVERSITY_DELACT = 51;                            //            |—删除大学
    public static final int SYSTEM_UNIVERSITY_GETPERPROVCITIES = 97;                  //            |—加载各省城市
    public static final int SYSTEM_BANKS_INDEX = 40;                                  //        |—银行名称管理
    public static final int SYSTEM_BANKS_ADD = 52;                                    //            |—添加银行
    public static final int SYSTEM_BANKS_EDIT = 53;                                   //            |—编辑银行
    public static final int SYSTEM_BANKS_SEARCH = 54;                                 //            |—查找银行
    public static final int SYSTEM_COURSEPRICE_INDEX = 129;                           //        |—课程价格管理
    //    public static final int SYSTEM_HOME_HOME = 19;                            //    |—校区管理
    public static final int SYSTEM_CAMPUS_INDEX = 41;                                 //        |—校区管理
    public static final int SYSTEM_CAMPUS_ADD = 70;                                   //            |—添加校区
    public static final int SYSTEM_CAMPUS_EDIT = 71;                                  //            |—编辑校区
    public static final int SYSTEM_CAMPUS_DELACT = 72;                                //            |—停启用校区
    public static final int SYSTEM_CAMPUS_SEARCH = 73;                                //            |—查询校区
    public static final int SYSTEM_BANKCARD_INDEX = 42;                               //        |—收/退款卡管理
    public static final int SYSTEM_BANKCARD_ADD = 55;                                 //            |—添加银行卡
    public static final int SYSTEM_BANKCARD_DELETE = 56;                              //            |—删除银行卡
    public static final int SYSTEM_ALIPAY_INDEX = 43;                                 //        |—支付宝帐号管理
    public static final int SYSTEM_ALIPAY_ADD = 57;                                   //            |—添加支付宝
    public static final int SYSTEM_ALIPAY_DELETE = 58;                                //            |—删除支付宝
    public static final int SYSTEM_PROMOTION_INDEX = 44;                              //        |—课程优惠设置
    public static final int SYSTEM_PROMOTION_ADD = 59;                                //            |—增加校区优惠
    public static final int SYSTEM_PROMOTION_DELETE = 60;                             //            |—删除校区优惠
    //    public static final int SYSTEM_HOME_HOME = 20;                            //    |—个人中心
    public static final int SYSTEM_PERSONAL_INDEX = 45;                               //        |—个人信息
    public static final int SYSTEM_PERSONAL_MODIFYPASSWORD = 156;                     //            |—修改密码
    public static final int SYSTEM_NOTIFICATION_INDEX = 46;                           //        |—消息提醒
    public static final int SYSTEM_HOME_HOME = 143;                                   //    |—数据导入
    public static final int SYSTEM_UPLOADEXCEL_STUDENT = 144;                         //        |—市场-学员登记数据导入
    public static final int SYSTEM_UPLOADEXCEL_OPENCLASS = 145;                       //        |—市场-公开课数据导入
    public static final int SYSTEM_UPLOADEXCEL_REGISTER = 146;                        //        |—市场-报名数据导入
    public static final int SYSTEM_UPLOADEXCEL_CLASSES = 147;                         //        |—教学-班级数据导入
    public static final int SYSTEM_UPLOADEXCEL_SIGN = 148;                            //        |—教学-签到数据导入
    public static final int SYSTEM_UPLOADEXCEL_IMPORTMARKETTARGET = 154;              //        |—市场-红线冲刺目标导入
    public static final int SYSTEM_UPLOADEXCEL_IMPORTEDUCATIONTARGET = 155;           //        |—教学-红线冲刺目标导入

}
